name: "Filebeat"
filebeat.inputs:
- type: filestream
  paths:
    - ${path.config}/logs/filebeat-*.ndjson
  parsers:
    - ndjson:
        keys_under_root: true
output.elasticsearch:
  hosts: [ "https://es01:9200" ]
  username: '${ELASTICSEARCH_USERNAME}'
  password: '${ELASTICSEARCH_PASSWORD}'
  ssl.certificate_authorities: config/certs/ca/ca.crt
monitoring:
  enabled: true
  elasticsearch:
    hosts: [ "https://es01:9200" ]
    username: '${MONITORING_USERNAME}'
    password: '${MONITORING_PASSWORD}'
    ssl.certificate_authorities: config/certs/ca/ca.crt