# /etc/traefik/traefik.yml
api:
  dashboard: true
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
providers:
  # docker:
    # defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
    # exposedbydefault: false
  file:
    directory: "/etc/traefik/conf"
log:
  filePath: "/var/log/traefik.json"
  format: json
  level: DEBUG
accessLog:
  filePath: "/var/log/access.log"
  filters:
    statusCodes:
      - "401"