# /etc/traefik/conf/kibana_dynamic.yml
http:
  routers:
    kibana:
      entryPoints:
        - websecure
      rule: Host(`kibana.localhost`) || PathPrefix(`/xyz`)
      middlewares:
        - kibana-auth
        - kibana-stripprefix
      service: kibana-service
      tls: {}
  middlewares:
    kibana-auth:
      basicAuth:
        usersFile: etc/traefik/conf/kibana.htpasswd
    kibana-stripprefix:
      stripPrefix:
        prefixes:
          - "/xyz"
  services:
    kibana-service:
      loadBalancer:
        servers:
        - url: "http://kibana:5601"