# Cluster
cluster.name: elastic
# Node
node.name: es01
# Memory
bootstrap.memory_lock: true
# Network
network.host: "0"
# Discovery
discovery.type: single-node
# Generate Trial License
xpack.license.self_generated.type: trial
# Enable Legacy Monitoring
xpack.monitoring.collection.enabled: true